#!/bin/bash

if [ $1 == "rbelya" ];then
	sed -i -- 's/rbelya/rbelya/g' *
elif [ $2 == "rbelya" ];then
	sed -i -- 's/rbeyla/rbelya/g' *
else 
	echo "Wrong input"
fi

gcc -o Login.cgi Login.c
chmod 755 Login.cgi
